name: Maze
author: EschieEsh
description: a plugin for generating labyrinths
version: 1.0.0
main: Maze\Main
api: 2.0.0
commands:
  maze:
    description: a command for generating mazes
    permission: maze.cmd
permissions:
  maze.cmd:
    default: op
    description: "Allow the use of /maze"
